staging:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
#  - dpl --provider=heroku --app=quanlykhachsan --api-key=$HEROKU_STAGING_API_KEY
  - dpl --provider=heroku --app=quanlykhachsan --api-key=8a2e50e0-a928-456e-b9e5-860e4d59046f
  only:
  - development

production:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=production-quanlykhachsan --api-key=8a2e50e0-a928-456e-b9e5-860e4d59046f
  only:
  - master